name: Build and Install

on:
    workflow_dispatch:

jobs:
    build_phosh:
        strategy:
          matrix:
            include:
              - device: pinephone
              - device: pinephonepro
            
        runs-on: ubuntu-latest #${{ matrix.settings.platform }#}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          #- name: Install tools
          #  if: matrix.settings.platform == 'self-hosted'
          #  run: |
          #    sudo pacman -Syu --noconfirm
          #    sudo pacman -S --noconfirm devtools \
          #      lsof \
          #      wget \
          #      fdisk \
          #      bsdtar
          - name: Install tools
            run: |
              sudo apt-get update
              sudo apt-get install -y lsof wget util-linux libarchive-tools e2fsprogs dosfstools arch-install-scripts fdisk
          - name: Run build script
            run: |
              chmod +x ./build.sh
              ./build.sh -u phosh -d ${{ matrix.device }} -a aarch64
              mv build/*.img ./${{device}}-phosh-archlinux.img
          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              name: ${{ matrix.device }}-phosh-archlinux.img
              path: ./${{ matrix.device }}-phosh-archlinux.img
    build_plasma_desktop:
        strategy:
          matrix:
            include:
              - device: pinetab2
              - device: pinetab
            
        runs-on: ubuntu-latest #${{ matrix.settings.platform }#}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          #- name: Install tools
          #  if: matrix.settings.platform == 'self-hosted'
          #  run: |
          #    sudo pacman -Syu --noconfirm
          #    sudo pacman -S --noconfirm devtools \
          #      lsof \
          #      wget \
          #      fdisk \
          #      bsdtar
          - name: Install tools
            run: |
              sudo apt-get update
              sudo apt-get install -y lsof wget util-linux libarchive-tools e2fsprogs dosfstools arch-install-scripts fdisk
          - name: Run build script
            run: |
              chmod +x ./build.sh
              ./build.sh -u plasma_desktop -d ${{ matrix.device }} -a aarch64
              mv build/*.img ./${{device}}-plasma-desktop-archlinux.img
          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              name: ${{ matrix.device }}-plasma-desktop-archlinux.img
              path: ./${{ matrix.device }}-plasma-desktop-archlinux.img
    build_sxmo:
        strategy:
          matrix:
            include:
              - device: pinephone
              - device: pinephonepro
            
        runs-on: ubuntu-latest #${{ matrix.settings.platform }#}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          #- name: Install tools
          #  if: matrix.settings.platform == 'self-hosted'
          #  run: |
          #    sudo pacman -Syu --noconfirm
          #    sudo pacman -S --noconfirm devtools \
          #      lsof \
          #      wget \
          #      fdisk \
          #      bsdtar
          - name: Install tools
            run: |
              sudo apt-get update
              sudo apt-get install -y lsof wget util-linux libarchive-tools e2fsprogs dosfstools arch-install-scripts fdisk
          - name: Run build script
            run: |
              chmod +x ./build.sh
              ./build.sh -u sxmo -d ${{ matrix.device }} -a aarch64
              mv build/*.img ./${{device}}-sxmo-archlinux.img
          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              name: ${{ matrix.device }}-sxmo-archlinux.img
              path: ./${{ matrix.device }}-sxmo-archlinux.img
    build_plasma_mobile:
        strategy:
          matrix:
            include:
              - device: pinephone
              - device: pinephonepro
            
        runs-on: ubuntu-latest #${{ matrix.settings.platform }#}
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          #- name: Install tools
          #  if: matrix.settings.platform == 'self-hosted'
          #  run: |
          #    sudo pacman -Syu --noconfirm
          #    sudo pacman -S --noconfirm devtools \
          #      lsof \
          #      wget \
          #      fdisk \
          #      bsdtar
          - name: Install tools
            run: |
              sudo apt-get update
              sudo apt-get install -y lsof wget util-linux libarchive-tools e2fsprogs dosfstools arch-install-scripts fdisk
          - name: Run build script
            run: |
              chmod +x ./build.sh
              ./build.sh -u plasma -d ${{ matrix.device }} -a aarch64
              mv build/*.img ./${{device}}-plasma-mobile-archlinux.img
          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              name: ${{ matrix.device }}-plasma-mobile-archlinux.img
              path: ./${{ matrix.device }}-plasma-mobile-archlinux.img
          
